using UnityEngine;

/// <summary>
/// Stores all baked forest cluster data as a flat asset.
/// Each instance is a pre-baked TRS Matrix4x4 (base rotation + random Y + scale already applied).
/// Generated by ForestBakerEditor, consumed at runtime by GPUForestRenderer.
/// Zero GameObjects are ever created from this data.
/// </summary>
[CreateAssetMenu(fileName = "ForestData_Island", menuName = "Age of Guilds/Forest Data")]
public class ForestData : ScriptableObject
{
    /// <summary>
    /// Pre-baked TRS matrices. Each one is a fully-corrected objectToWorld transform.
    /// Stored flat as float[] (16 floats per matrix) for efficient GPU upload.
    /// </summary>
    [HideInInspector]
    public float[] matrixData; // length = Count * 16

    [HideInInspector]
    public int instanceCount;

    public int Count => instanceCount;
}
